apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-helloworld
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: hicham7farhi/hello-world:0.0.5
        name: hello-world
status: {}
